SMALL_KEYWORDS = [
        "american hairless terrier",
        "australian silky terrier",
        "chin",
        "english toy terrier",
        "japanischer terrier",
        "lancashire heeler",
        "norsk lundehund",
        "patterdale-terrier",
        "perro sin pelo del peru (pequeno)",
        "petit brabancon",
        "podengo portugues kurzhaar pequeno",
        "podengo portugues rauhhaar pequeno",
        "rat terrier",
        "skye terrier",
        "volpino italiano",
        "xoloitzcuintle miniatura",
        "zwergschäferhund",
        "affenpinscher",
        "bichon",
        "biewer",
        "bologneser",
        "bolonka",
        "cairn terrier",
        "cavalier king charles",
        "chihuahua",
        "chinese crested",
        "coton de tulear",
        "dackel",
        "dachshund",
        "französische bulldogge",
        "griffon",
        "havaneser",
        "italienisches windspiel",
        "king charles spaniel",
        "kleinspitz",
        "kurzhaar dachshund kaninchen",
        "kurzhaar dachshund zwerg",
        "langhaar dachshund kaninchen",
        "langhaar dachshund zwerg",
        "lhasa apso",
        "löwchen",
        "malteser",
        "miniatur bull terrier",
        "mops",
        "norfolk terrier",
        "norwich terrier",
        "papillon",
        "pekingese",
        "phalene",
        "prager rattler",
        "rauhhaar dachshund kaninchen",
        "rauhhaar dachshund zwerg",
        "russkiy toy",
        "schipperke",
        "shih tzu",
        "tibetan spaniel",
        "toypudel",
        "west highland white terrier",
        "yorkshire terrier",
        "zwergpinscher",
        "zwergpudel",
        "zwergschnauzer",
        "zwergspitz",
    ]

MEDIUM_KEYWORDS = [
        "american pocket bully",
        "american water spaniel",
        "anglo?francais de petite venerie",
        "aussiedoodle",
        "jura laufhund",
        "barbet",
        "berger de picardie",
        "berger des pyrenees",
        "berner niederlaufhund",
        "bosanski ostrodlaki gonic",
        "braque francais - type pyrenees",
        "bull terrier",
        "canaan dog",
        "carolina dog",
        "cesky fousek",
        "chodsky pes",
        "cirneco dell'etna",
        "clumber spaniel",
        "dalmatiner",
        "dandie dinmont terrier",
        "drentsche patrijshond",
        "drever",
        "elo",
        "erdelyi kopo",
        "gammel dansk hoensehund",
        "gonczy polski",
        "gordon setter",
        "gos d'atura catala",
        "hannoverscher schweisshund",
        "hellinikos ichnilatis",
        "hokkaido",
        "hollandse smoushond",
        "hrvatski ovcar",
        "irish glen of imaal terrier",
        "irish red setter",
        "irish red and white setter",
        "irish soft coated wheaten terrier",
        "irish terrier",
        "korea jindo dog",
        "laekenois",
        "lakeland terrier",
        "lapinporokoira",
        "lurcher",
        "luzerner laufhund",
        "norbottenspets",
        "norsk buhund",
        "norsk elghund",
        "ogar polski",
        "perdigueiro portugues",
        "perdigueiro de burgos",
        "perro de agua espanol",
        "perro sin pelo del peru (medio)",
        "petit bleu de gascogne",
        "podenco canario",
        "podenco ibicenco",
        "podengo portugues kurzhaar medio",
        "podengo portugues rauhhaar medio",
        "polski owczarek nizinny",
        "porcelaine",
        "posavski gonic",
        "russisch-europäischer laika",
        "schapendoes",
        "schweizerische niederlaufhunde",
        "schwyzer laufhund",
        "segugio italiano",
        "shikoku",
        "silken windsprite",
        "slovensky kopov",
        "srpski gonic",
        "srpski trobojni gonic",
        "stabyhoun",
        "sussex spaniel",
        "taiwan dog",
        "thai ridgeback dog",
        "västgötaspets",
        "wetterhoun",
        "xoloitzcuintle medio",
        "aidi",
        "airedale",
        "alpenländische dachsbracke",
        "american cocker spaniel",
        "american shepherd",
        "australian cattledog",
        "australian kelpie",
        "australian shepherd",
        "australian terrier",
        "basenji",
        "basset",
        "bayrischer gebirgsschweisshund",
        "beagle",
        "bearded collie",
        "bedlington terrier",
        "border collie",
        "border terrier",
        "boston terrier",
        "bracke",
        "brandlbracke",
        "bulldog",
        "cesky terrier",
        "cockerpoo",
        "collie",
        "dansk-svensk gardshund",
        "deutsch drahthaar",
        "deutsch kurzhaar",
        "deutsch langhaar",
        "deutsche bracke",
        "deutscher jagdterrier",
        "deutscher pinscher",
        "deutscher spitz",
        "deutscher wachtelhund",
        "english cocker spaniel",
        "english pointer",
        "english setter",
        "english springer spaniel",
        "entlebucher",
        "epagneul",
        "eurasier",
        "field spaniel",
        "finnen-spitz",
        "finnischer lapphund",
        "fox terrier",
        "galgo",
        "greyhound",
        "harzer fuchs",
        "islandhund",
        "jack russell",
        "jagdterrier",
        "kerry blue terrier",
        "klein- oder mittelpudel",
        "kleiner münsterländer",
        "kleinpudel",
        "kooikerhondje",
        "kromfohrländer",
        "lagotto",
        "labradoodle",
        "magyar vizsla",
        "malinois",
        "manchester terrier",
        "mittelspitz",
        "mudi",
        "nova scotia",
        "parson russell",
        "pinscher",
        "pudel",
        "puli",
        "pumi",
        "schnauzer",
        "scottish terrier",
        "shar pei",
        "shetland sheepdog",
        "shiba",
        "spitz",
        "staffordshire bullterrier",
        "terrier brasileiro",
        "tibetan terrier",
        "tiroler bracke",
        "whippet",
        "welsh corgi",
        "welsh springer spaniel",
        "welsh terrier",
        "österreichischer pinscher",
    ]

LARGE_KEYWORDS = [
        "american foxhound",
        "english foxhound",
        "ariegeois",
        "appenzeller gebirgsschweisshund",
        "azawakh",
        "berner laufhund",
        "billy",
        "bracco italiano",
        "braque saint-germain",
        "braque d'auvergne",
        "braque de l'ariege",
        "braque du bourbonnais",
        "braque francais - type gascogne",
        "cane da pastore bergamasco",
        "cao de agua portugues",
        "cao de castro laboreiro",
        "chart polski",
        "chesapeake bay retriever",
        "chinook",
        "cimarron uruguayo",
        "curly-coated retriever",
        "do-khyi",
        "english coonhound",
        "francais blanc et noir",
        "francais tricolore",
        "grand gascon saintongeois",
        "groenendael",
        "grosser münsterländer",
        "grönlandshund",
        "holländischer schäferhund",
        "irish water spaniel",
        "jämthund",
        "karelischer bärenhund",
        "krazski ovcar",
        "otterhound",
        "perro sin pelo del peru (grande)",
        "pharaoh hound",
        "polski owczarek podhalanski",
        "poitevin",
        "rafeiro do alentejo",
        "sandros leisha dog",
        "schwarzer terrier",
        "schweizerische laufhunde",
        "shiloh shepherd",
        "spinone italiano",
        "südrussischer ovtcharka",
        "tervueren",
        "tibetischer kyi apso",
        "westsibirischer laika",
        "xoloitzcuintle grande",
        "afghanischer windhund",
        "akita",
        "alaskan malamute",
        "american akita",
        "american bulldog",
        "american bully",
        "american staffordshire",
        "appenzeller sennenhund",
        "barsoi",
        "belgischer schäferhund",
        "berger blanc suisse",
        "berger de beauce",
        "berger de brie",
        "berner sennenhund",
        "black and tan coonhound",
        "boerboel",
        "bouvier",
        "broholmer",
        "bullmastiff",
        "cane corso",
        "catahoula",
        "chow-chow",
        "ciobanesc",
        "coban köpegi",
        "deerhound",
        "deutsche dogge",
        "deutscher boxer",
        "deutscher schäferhund",
        "dobermann",
        "dog de bordeaux",
        "dogo",
        "fila brasileiro",
        "flat-coated retriever",
        "golden retriever",
        "grosser schweizer sennenhund",
        "grosspudel",
        "grossspitz",
        "hovawart",
        "irish wolfhound",
        "kangal",
        "kaukasischer ovtcharka",
        "komondor",
        "kuvasz",
        "labrador retriever",
        "landseer",
        "leonberger",
        "magyar agar",
        "maremmano",
        "mastiff",
        "mastin",
        "neufundländer",
        "old english sheepdog",
        "olde english bulldogge",
        "pit bull",
        "pyrenäen berghund",
        "rhodesian ridgeback",
        "riesenschnauzer",
        "rottweiler",
        "saarlooswolfhond",
        "saluki",
        "samojede",
        "sarplaninac",
        "siberian husky",
        "sloughi",
        "st. bernhard",
        "tornjak",
        "tschechoslowakischer wolfhund",
        "weimaraner",
        "windhund",
        "wolfspitz",
        "zentralasiatischer ovtcharka",
    ]